apiVersion: v1
kind: Service
metadata:
  labels:
    service: etherpad
  name: etherpad
  namespace: test
spec:
  ports:
  - name: etherpad
    port: 9100
    targetPort: 9100
  selector:
    service: etherpad
status:
  loadBalancer: {}
