 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: webingress
   namespace: grafana
   annotations:
     kubernetes.io/ingress.class: "nginx"
     cert-manager.io/cluster-issuer: "letsencrypt-prod"
 spec:
   tls:
   - hosts:
     - grafana.devopsk8s.cf
     secretName: grafana-letsencrypt-tls
   rules:
   - host: grafana.devopsk8s.cf
     http:
       paths:
       - path: /
         backend:
           serviceName: grafana
           servicePort: 80
