#apiVersion: extensions/v1beta1
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: jibri
  name: jibri
  namespace: minikube
spec:
  selector:
    matchLabels:
      service: jibri
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: jibri
    spec:
      volumes:
        - name: dev-shm
          hostPath:
            path: /dev/shm
        - name: dev-snd
          hostPath:
            path: /dev/snd      
      containers:
      - env:
        - name: XMPP_SERVER
          value: 10.111.182.216
#value: prosody clusterip          
        - name: XMPP_DOMAIN
          value: minikube.devopsk8s.cf
        - name: XMPP_AUTH_DOMAIN
          value: auth.minikube.devopsk8s.cf
        - name: XMPP_INTERNAL_MUC_DOMAIN
          value: internal-muc.minikube.devopsk8s.cf
        - name: XMPP_RECORDER_DOMAIN
          value: recorder.minikube.devopsk8s.cf
        - name: JIBRI_XMPP_USER
          value: jibri
        - name: JIBRI_XMPP_PASSWORD
          value: password
        - name: JIBRI_BREWERY_MUC
          value: jibribrewery
        - name: JIBRI_RECORDER_USER
          value: recorder
        - name: JIBRI_RECORDER_PASSWORD
          value: password
        - name: JIBRI_RECORDING_DIR
          value: /config/recordings
        - name: JIBRI_FINALIZE_RECORDING_SCRIPT_PATH
          value: /config/finalize.sh
        - name: JIBRI_STRIP_DOMAIN_JID
          value: muc
        - name: JIBRI_LOGS_DIR
          value: /config/logs
        - name: DISPLAY
          value: :0
        - name: TZ
          value: Asia/Kolkata
        image: jitsi/jibri
        name: jibri
        securityContext:
          capabilities:
            add: ["SYS_ADMIN", "NET_BIND_SERVICE"]
        volumeMounts:
          - mountPath: /dev/shm
            name: dev-shm
          - mountPath: /dev/snd
            name: dev-snd
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "1000Mi"
            cpu: "1000m"                
      restartPolicy: Always
status: {}
