apiVersion: v1
kind: Service
metadata:
  labels:
    service: jvb
  name: jvb-tcp-udp
  namespace: test
spec:
  ports:
  - name: "4443"
    port: 4443
    targetPort: 4443
  - name: "10000"
    port: 10000
    protocol: UDP
    targetPort: 10000
  selector:
    service: jvb
status:
  loadBalancer: {}
