 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: webingress
   namespace: jitsi
   annotations:
     kubernetes.io/ingress.class: "nginx"
     cert-manager.io/cluster-issuer: "letsencrypt-prod"
 spec:
   tls:
   - hosts:
     - jitsi.devopsk8s.cf
     secretName: jitsi-letsencrypt-tls
   rules:
   - host: jitsi.devopsk8s.cf
     http:
       paths:
       - path: /
         backend:
           serviceName: web
           servicePort: 80
