apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: web
  name: web
  namespace: test
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: web
    spec:
      containers:
      - env:
        - name: JICOFO_AUTH_USER
          value: focus
        - name: XMPP_DOMAIN
          value: test.devopsk8s.cf
        - name: XMPP_AUTH_DOMAIN
          value: auth.test.devopsk8s.cf
        - name: XMPP_BOSH_URL_BASE
          value: http://prosody:5280
        - name: XMPP_MUC_DOMAIN
          value: muc.test.devopsk8s.cf
        - name: TZ
          value: Asia/Kolkata
        image: jitsi/web
        name: web
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
status: {}
