 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: elasticsearch-ingress
   annotations:
     kubernetes.io/ingress.class: "nginx"
     cert-manager.io/cluster-issuer: "letsencrypt-prod"
 spec:
   rules:
   - host: elasticsearch.devopsk8s.cf
     http:
       paths:
       - path: /
         backend:
           serviceName: elasticsearch-master
           servicePort: 9200
