 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: kibana-ingress
   annotations:
     kubernetes.io/ingress.class: "nginx"
     cert-manager.io/cluster-issuer: "letsencrypt-prod"
 spec:
   tls:
   - hosts:
     - kibana.devopsk8s.cf
     secretName: kibana-letsencrypt-tls
   rules:
   - host: kibana.devopsk8s.cf
     http:
       paths:
       - path: /
         backend:
           serviceName: kibana-kibana 
           servicePort: 5601
